Bank/Models/ErrorViewModel.cs
using System;

namespace Bank.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Bank/Controllers/BankController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using BankManagement.BLL;
using BankManagement.DTO;
using Microsoft.AspNetCore.Mvc;

namespace Bank.Controllers
{
    public class BankController : Controller
    {
        private readonly IBank _bank;
        public BankController(IBank bank)
        {
            _bank = bank;
        }

        public IActionResult Index()
        {
            return View();
        }
        BankDetail bankDetail = new BankDetail();

        [HttpGet]
        public IActionResult ShowAllBankDetail()
        {
            List<BankDetail> BankList = new List<BankDetail>();
            BankList = _bank.ShowAllBankDetail();

            return View(BankList);

        }

        [HttpGet]
        public IActionResult GetBankDetail(int accountNumber)
        {
            
            bankDetail = _bank.GetSingleBankAccountDetail(accountNumber);

            return View(bankDetail);
           
        }
     //[httpGet]
        public IActionResult AddBankDetail(BankDetail bankDetail)
        {   
            _bank.AddBankDetail(bankDetail);       
            return View(bankDetail);
        }
        //[HttpPut]
        public IActionResult UpdateBankDetail(int accountNumber, string CustomerEmail , string CustomerPhoneNumber)
        {
            _bank.UpdatebankDetail(accountNumber , CustomerEmail , CustomerPhoneNumber);
            return View(bankDetail);        
        }
    //    [HttpDelete]
        public IActionResult DeleteBankDetail(int accountNumber)
        {
            _bank.DeleteBankDetail(accountNumber);
            return View(bankDetail);
          
        }
     
    }
}

Bank/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Bank.Models;

namespace Bank.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Bank/Views/Bank/AddBankDetail.cshtml
@model BankManagement.DTO.BankDetail

@{
    ViewData["Title"] = "AddBankDetail";
}

<h2>AddBankDetail</h2>

<h4>BankDetail</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddBankDetail">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="AccountNumber" class="control-label"></label>
                <input asp-for="AccountNumber" class="form-control" />
                <span asp-validation-for="AccountNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AccountType" class="control-label"></label>
                <input asp-for="AccountType" class="form-control" />
                <span asp-validation-for="AccountType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerName" class="control-label"></label>
                <input asp-for="CustomerName" class="form-control" />
                <span asp-validation-for="CustomerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NomieeName" class="control-label"></label>
                <input asp-for="NomieeName" class="form-control" />
                <span asp-validation-for="NomieeName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerAddress" class="control-label"></label>
                <input asp-for="CustomerAddress" class="form-control" />
                <span asp-validation-for="CustomerAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerEmail" class="control-label"></label>
                <input asp-for="CustomerEmail" class="form-control" />
                <span asp-validation-for="CustomerEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerPhoneNumber" class="control-label"></label>
                <input asp-for="CustomerPhoneNumber" class="form-control" />
                <span asp-validation-for="CustomerPhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Bank/Views/Bank/DeleteBankDetail.cshtml
@model BankManagement.DTO.BankDetail

@{
    ViewData["Title"] = "DeleteBankDetail";
}

<h2>DeleteBankDetail</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BankDetail</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AccountNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AccountNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AccountType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AccountType)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CustomerName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CustomerName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NomieeName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NomieeName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CustomerAddress)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CustomerAddress)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CustomerEmail)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CustomerEmail)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CustomerPhoneNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CustomerPhoneNumber)
        </dd>
    </dl>
    
    <form asp-action="DeleteBankDetail">
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Bank/Views/Bank/GetBankDetail.cshtml
@model BankManagement.DTO.BankDetail

@{
    ViewData["Title"] = "GetBankDetail";
}

<h2>GetBankDetail</h2>

<div>
    <h4>BankDetail</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AccountNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AccountNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AccountType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AccountType)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CustomerName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CustomerName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NomieeName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NomieeName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CustomerAddress)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CustomerAddress)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CustomerEmail)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CustomerEmail)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CustomerPhoneNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CustomerPhoneNumber)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

Bank/Views/Bank/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

Bank/Views/Bank/ShowAllBankDetail.cshtml
@model IEnumerable<BankManagement.DTO.BankDetail>

@{
    ViewData["Title"] = "ShowAllBankDetail";
}

<h2>ShowAllBankDetail</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.AccountNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AccountType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CustomerName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NomieeName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CustomerAddress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CustomerEmail)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CustomerPhoneNumber)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AccountNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AccountType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NomieeName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerEmail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerPhoneNumber)
            </td>
            <td>
                @Html.ActionLink("Edit", "UpdatebankDetail", new { item.AccountNumber, item.CustomerEmail, item.CustomerPhoneNumber }) |
                @Html.ActionLink("Details", "GetBankDetail", new { item.AccountNumber }) |
                @Html.ActionLink("Delete", "DeleteBankDetail", new { item.AccountNumber })
                @Html.ActionLink("Add", "AddBankDetail", new {})
            </td>
        </tr>
}
    </tbody>
</table>

Bank/Views/Bank/UpdatebankDetail.cshtml
@model BankManagement.DTO.BankDetail

@{
    ViewData["Title"] = "UpdatebankDetail";
}

<h2>UpdatebankDetail</h2>

<h4>BankDetail</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="UpdateBankDetail">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="AccountNumber" class="control-label"></label>
                <input asp-for="AccountNumber" class="form-control" />
                <span asp-validation-for="AccountNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerEmail" class="control-label"></label>
                <input asp-for="CustomerEmail" class="form-control" />
                <span asp-validation-for="CustomerEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerPhoneNumber" class="control-label"></label>
                <input asp-for="CustomerPhoneNumber" class="form-control" />
                <span asp-validation-for="CustomerPhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Bank/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Bank/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Bank/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

Bank/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bank</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Bank</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="Bank" asp-action="ShowAllBankDetail">AllDetail</a></li>
               
                    <li><a asp-area="" asp-controller="Bank" asp-action="AddBankDetail">AddDetail</a></li>

                    <li><a asp-area="" asp-controller="Bank" asp-action="UpdateBankDetail">UpdateDetail</a></li>
           
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - Bank</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>